# Generated by Django 4.0.2 on 2022-02-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoursProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HonoursProject',
            new_name='Session',
        ),
    ]
