# Generated by Django 4.0.2 on 2022-02-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honoursProject', '0002_rename_honoursproject_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sessionID',
            new_name='join_code',
        ),
    ]
