# Generated by Django 4.0.2 on 2022-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honoursProject', '0003_rename_sessionid_session_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ascendToken',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
