# Generated by Django 4.0.2 on 2022-04-07 18:45

from django.db import migrations, models
import honoursProject.models


class Migration(migrations.Migration):

    dependencies = [
        ('honoursProject', '0005_alter_session_ascendtoken_alter_session_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ascendToken',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='session',
            name='join_code',
            field=models.CharField(blank=True, default=honoursProject.models.create_random_code, max_length=6),
        ),
    ]
